micronaut:
  application:
    name: demo
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
endpoints:
  all:
    enabled: true
    sensitive: false
